name: Bhagya
description: "Bhagya - Your Daily Cosmic Guide"
publish_to: "none"
version: 1.0.1+3

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.0.0
  flutter_riverpod: ^2.5.0
  shared_preferences: ^2.2.0
  google_fonts: ^6.1.0
  intl: ^0.20.2
  share_plus: ^10.1.0
  url_launcher: ^6.2.0
  flutter_tts: ^4.0.0
  http: ^1.2.0
  razorpay_flutter: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

dependency_overrides:
  fluttertoast: ^8.2.10
  web: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#1A0A2E"
  adaptive_icon_foreground: "assets/icon.png"
  web:
    generate: true
    image_path: "assets/icon.png"
